name: Migration apply
on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Configure build environment
        run: |
          sudo apt-get update && sudo apt-get install -y wget curl unzip
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
      - name: Install Goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Verify Goose installation
        run: |
          goose --version
          if [ $? -ne 0 ]; then
            echo "Goose is not installed correctly. Exiting."
            exit 1
          fi
      - name: Set up environment variables
        run: |
          export GOOSE_MIGRATIONS_DIR=./migrations
          export GOOSE_DRIVER=postgres
          export GOOSE_DBSTRING="postgres://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
          export PGPASSWORD=${{ secrets.DB_PASSWORD }}

      # Configurar variáveis de ambiente
      - name: Set up environment variables
        run: |
          echo "GOOSE_MIGRATIONS_DIR=./migrations" >> $GITHUB_ENV
          echo "GOOSE_DRIVER=postgres" >> $GITHUB_ENV
          echo "GOOSE_DBSTRING=postgres://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "PGPASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
      - name: Check if migrations are needed
        run: |
          if ! goose -s status | grep -q "Pending"; then
            echo "No pending migrations found."
            exit 0
          fi
      - name: Apply migrations
        run: |
          goose -s up
          goose -s status

  rollback:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rollback migrations
        run: |
          goose -s down
          goose -s status