name: Migration apply
on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Goose
        run: |
          curl -sf https://raw.githubusercontent.com/pressly/goose/main/install.sh | sh
      - name: Set up environment variables
        run: |
          export GOOSE_MIGRATIONS_DIR="./migrations"
          export DB_URL="postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:{{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
          export PGPASSWORD=${{ secrets.DB_PASSWORD }}
      - name: Check if migrations are needed
        run: |
          if ! goose -s status | grep -q "Pending"; then
            echo "No pending migrations found."
            exit 0
          fi
      - name: Apply migrations
        run: |
          goose -s up
          goose -s status

  rollback:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rollback migrations
        run: |
          goose -s down
          goose -s status