name: Migration apply
on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: golangci/golangci-lint-action@v1
        with:
          version: latest
      - name: Install Goose
        run: |
          go install github.com/pressly/goose/cmd/goose@latest
          which goose
      - name: Verify Goose installation
        run: |
          goose --version
          if [ $? -ne 0 ]; then
            echo "Goose is not installed correctly. Exiting."
            exit 1
          fi
      - name: Set up environment variables
        run: |
          export GOOSE_MIGRATIONS_DIR="./migrations"
          export DB_URL="postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:{{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
          export PGPASSWORD=${{ secrets.DB_PASSWORD }}
      - name: Check if migrations are needed
        run: |
          if ! goose -s status | grep -q "Pending"; then
            echo "No pending migrations found."
            exit 0
          fi
      - name: Apply migrations
        run: |
          goose -s up
          goose -s status

  rollback:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rollback migrations
        run: |
          goose -s down
          goose -s status