name: Pre-deployment pipeline

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod download

      - name: Execute tests
        run: |
          go test -coverprofile=coverage.out ./...

      - name: Convert coverage to XML
        run: |
          go tool cover -func=coverage.out > coverage.xml