name: Pre-deployment pipeline

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.23
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...